defaults:
  - encoder: Any

instance:
  _target_: models.networks.JEPAAny.JEPAAnyMulti
  encoder: ${model.network.encoder}
  predictor:
    _target_: models.networks.encoder.Transformer.VisionTransformerPredictorMulti
    num_patches: ${dataset.num_patches}
    embed_dim: ${model.network.encoder.embed_dim}
    predictor_embed_dim: ${model.network.encoder.embed_dim}
    depth: 4
    num_heads: 16
    mlp_ratio: 4.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    scales: ${dataset.scales}
  ratio: 0.5
  
  