defaults:
  - network: Monomodal
  - loss: bce
  - train_metrics: metrics_mono
  - val_metrics: metrics_mono
  - test_metrics: metrics_mono
  - _self_

name: PseTae

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 20
  max_epochs: ${max_epochs}

instance:
  _target_: src.models.module.Module
  optimizer: ${model.optimizer}
  scheduler: ${model.scheduler}
  network: ${model.network}
  loss: ${model.loss}
  train_metrics: ${model.train_metrics}
  val_metrics: ${model.val_metrics}
  test_metrics: ${model.test_metrics}