defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: burnscars
global_batch_size: 128
num_classes: 2
height: 1536
width: 1536
num_patches: 2359296
norm_path: ${data_dir}

train_dataset:
  _partial_: true
  _target_: data.BurnScar.BurnScar
  path: ${data_dir}
  split: train
  transform: ${dataset.train_transform}
  modalities: ${modalities}
  norm_path: ${dataset.norm_path}

val_dataset:
  _partial_: true
  _target_: data.BurnScar.BurnScar
  path: ${data_dir}
  split: val
  transform: ${dataset.test_transform}
  modalities: ${modalities}
  norm_path: ${dataset.norm_path}

test_dataset:
  _partial_: true
  _target_: data.BurnScar.BurnScar
  path: ${data_dir}
  split: test
  transform: ${dataset.test_transform}
  modalities: ${modalities}
  norm_path: ${dataset.norm_path}