defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: MultiPlanted
num_classes: 40
global_batch_size: 
  tsaits: 128
  pastishd: 2
  flair: 64
  planted: 256
  s2naip: 4
shapes:
  tsaits: 6
  pastishd: 128
  flair: 10
  planted: 12
  s2naip: 64
num_patches:
  tsaits: 36
  pastishd: 16384
  flair: 100
  planted: 144

iter: ${eval:'1075701 // (${dataset.global_batch_size.planted} * ${trainer.devices} * ${trainer.trainer.num_nodes})'}

train_dataset:
  _partial_: true
  _target_: data.MultiDataset.MultiDataset
  scales: ${dataset.scales}
  datasets:
    planted:
      _target_: data.Planted.Planted
      path: ${paths.data_dir}/Planted/
      split: train
      transform: ${dataset.train_transform}
      classes: ${dataset.planted.classes}
      partition: ${partition}
      modalities: ${modalities_dict.planted}
      norm_path: ${paths.data_dir}/Planted
      density_sampling: False

val_dataset:
  _partial_: true
  _target_: data.MultiDataset.MultiDataset
  scales: ${dataset.scales}
  datasets:
    planted: 
      _target_: data.Planted.Planted
      path: ${paths.data_dir}/Planted/
      split: val
      transform: ${dataset.test_transform}
      classes: ${dataset.planted.classes}
      partition: 1.0
      modalities: ${modalities_dict.planted}
      norm_path: ${paths.data_dir}/Planted

test_dataset:
  _partial_: true
  _target_: data.MultiDataset.MultiDataset
  scales: ${dataset.scales}
  datasets:
    planted: 
      _target_: data.Planted.Planted
      path: ${paths.data_dir}/Planted/
      split: test
      transform: ${dataset.test_transform}
      classes: ${dataset.planted.classes}
      partition: 1.0
      modalities: ${modalities_dict.planted}
      norm_path: ${paths.data_dir}/Planted

scales:
  planted:
    - 3

planted:
  classes: ["Elaeis guineensis", 
        "Pinus taeda", 
        "Pinus rigida", 
        "Pinus koraiensis", 
        "Pinus densiflora",
        "Abies sachalinensis",
        "Pinus elliottii",
        "Shorea robusta",
        "Castanea crenata",
        "Pseudotsuga menziesii",
        "Eucalyptus globulus",
        "Pinus radiata",
        "Robinia pseudoacacia",
        "Pinus thunbergii",
        "Pinus echinata",
        "Thea sinensis",
        "Betula pendula",
        "Hevea brasiliensis",
        "Picea glehnii",
        "Quercus acutissima",
        "Eucalyptus nitens",
        "Cocos nucifera",
        "Anacardium occidentale",
        "Zelkova serrata",
        "Acer pictum",
        "Prunus serrulata",
        "Prunus dulcis",
        "Picea jezoensis",
        "Quercus variabilis",
        "Fraxinus rhynchophylla",
        "Ginkgo biloba",
        "Pasania edulis",
        "Dendropanax morbiferus",
        "Machilus thunbergii",
        "Cryptomeria japonica",
        "Acacia melanoxylon",
        "Malus pumila",
        "Picea mariana",
        "Cornus controversa",
        "Theobroma cacao"]