# @package _global_

defaults:
  - override /dataset: BioMassters
  - override /model/network/encoder: Any_Base
  - override /model/network: Fine_tuning_SemSeg
  - override /model/loss: mse
  - override /model/train_metrics: metrics_reg
  - override /model/val_metrics: metrics_reg
  - override /model/test_metrics: metrics_reg

model:
  name: "AnySat_FineTuning_MM_SemSeg"
  optimizer:
    lr: 2e-4
  network:
    encoder:
      scale: 1
      keep_subpatch: True
      modality_keep: "s1"
    instance:
      freeze: True
      name: "target_encoder"
      path: ${paths.root_dir}/.models/AnySat_Base.pth

callbacks:
  early_stopping:
    monitor: "val/RMSE"
    mode: "min"
    patience: 10

modalities:
  - "s2"
  - "s1"