# @package _global_

defaults:
  - override /dataset: FLAIR
  - override /dataset/test_transform: Identity
  - override /model/network/encoder: Any_Base
  - override /model: SemSeg
  - override /model/network: SemSeg_FLAIR
  - override /model/network/mlp: mlpDenseSemSegFLAIR

dataset:
  classif: False

model:
  name: "Any_MM"
  optimizer:
    lr: 5e-5
  network:
    encoder:
      scale: 1
      keep_subpatch: True
      modality_keep: "aerial-flair"
    mlp:
      instance:
        initial_dim: ${model.network.encoder.embed_dim}

callbacks:
  early_stopping:
    monitor: "val/mIoU"
    mode: "max"
    patience: 10

modalities:
  - "aerial-flair"
  - "s2"

