# @package _global_

defaults:
  - override /dataset: MultiFLAIR
  - override /model: JEPA_multi
  - override /model/network: JEPAAny_multi
  - override /model/network/encoder: Any_Base_multi
  - override /model/loss: AnySAT_JEPA

datamodule:
  _target_: data.datamodule.DataModuleMulti

dataset:
  global_batch_size: 
    flair: 16

model:
  name: "AnySat"
  optimizer:
    lr: 5e-5

callbacks:
  early_stopping:
    patience: 200

modalities_dict:
  flair:
    - "aerial-flair"
    - "s2"
