# @package _global_

defaults:
  - override /dataset: Pastis
  - override /model/network/encoder: Any_Base
  - override /model: SemSeg
  - override /model/network: Fine_tuning_SemSeg
  #- override /model/test_metrics: metrics_SemSeg_visu

dataset:
  classif: False

model:
  name: "AnySat_FineTuning_MM_SemSeg"
  optimizer:
    lr: 5e-5
  network:
    encoder:
      scale: 4
    instance:
      name: "target_encoder"
      path: ${paths.log_dir}/PASTIS-R_OmniSAT/checkpoints/last.ckpt

callbacks:
  early_stopping:
    monitor: "val/mIoU"
    mode: "max"
    patience: 10

modalities:
  - "spot"
  - "s2"
  - "s1"