# @package _global_

defaults:
  - override /dataset: MultiPastis
  - override /model: JEPA_multi
  - override /model/network: JEPAOmni_multi
  - override /model/network/encoder: Any_Base_multi
  - override /model/loss: OmniSAT_JEPA

datamodule:
  _target_: data.datamodule.DataModuleMulti
model:
  name: "AnySat"
  optimizer:
    lr: 5e-5

callbacks:
  early_stopping:
    patience: 200

modalities_dict:
  pastishd:
    - "spot"
    - "s2"
    - "s1"
