# @package _global_

defaults:
  - override /dataset: MultiPlanted
  - override /model: JEPA_multi
  - override /model/network: JEPAAny_multi
  - override /model/network/encoder: Any_Base_multi
  - override /model/loss: AnySat_JEPA

datamodule:
  _target_: data.datamodule.DataModuleMulti
model:
  name: "AnySat"
  optimizer:
    lr: 5e-5

callbacks:
  early_stopping:
    patience: 200

modalities_dict:
  planted:
    - "s2"
    - "s1"
    - "l7"
    - "alos"
    - "modis"
