# @package _global_

defaults:
  - override /dataset: S2Naip
  - override /model/network: Unet
  - override /model: SemSeg
  - override /model/loss: crossentropy_flair

model:
  name: "UTT"
  optimizer:
    lr: 0.001

callbacks:
  early_stopping:
    monitor: "val/mIoU"
    mode: "max"
    patience: 10

modalities:
  - "naip"