# @package _global_

defaults:
  - override /dataset: S2Naip
  - override /model/network: Unet
  - override /model: SemSeg
  - override /model/loss: CrossEntropyIgnore

model:
  name: "Unet"
  optimizer:
    lr: 0.001

callbacks:
  early_stopping:
    monitor: "val/mIoU"
    mode: "max"
    patience: 10

modalities:
  - "naip"