# @package _global_

defaults:
  - override /dataset: S2Naip
  - override /model/network/encoder: Any_Base
  - override /model: SemSeg
  - override /model/loss: crossentropy_flair
  - override /model/network/mlp: mlpDenseSemSegFLAIR

datamodule:
  stop_iteration_train: ${dataset.iter}
  stop_iteration_val: ${dataset.iter_val}

model:
  name: "Any_MM"
  optimizer:
    lr: 2e-4
  network:
    encoder:
      scale: 1
      keep_subpatch: True
      modality_keep: "naip"
    mlp:
      instance:
        initial_dim: ${model.network.encoder.embed_dim}
        resolution: 1.25
        proj_size: 8

callbacks:
  early_stopping:
    monitor: "val/mIoU"
    mode: "max"
    patience: 10

modalities:
  - "naip"
  - "l8"
  - "s2"
  - "s1"

